# Generated by Django 5.0.4 on 2024-04-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publivada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publivada',
            new_name='publicada',
        ),
    ]
